---
vaultwarden_version: "1.29.2"
vaultwarden_config_dir: "/opt/vaultwarden/data"
vaultwarden_config_file: "{{ vaultwarden_config_dir }}/config.json"
vaultwarden_user: "vaultwarden"

vaultwarden_container_name: "vaultwarden"
vaultwarden_container_image_reference: >-
  {{
    vaultwarden_container_image_repository
    + ':'
    + vaultwarden_container_image_tag | default(vaultwarden_version + '-alpine', true)
  }}
vaultwarden_container_image_repository: >-
  {{
    (
      container_registries[vaultwarden_container_image_registry]
      | default(vaultwarden_container_image_registry)
    )
    + '/'
    + vaultwarden_container_image_namespace | default('')
    + vaultwarden_container_image_name
  }}
vaultwarden_container_image_registry: "docker.io"
vaultwarden_container_image_namespace: "vaultwarden/"
vaultwarden_container_image_name: "server"
# vaultwarden_container_image_tag

vaultwarden_container_default_env: []
vaultwarden_container_etc_hosts: ~
vaultwarden_container_networks: ~
vaultwarden_container_restart_policy: unless-stopped
vaultwarden_container_ports:
  - "80/tcp"

vaultwarden_http_proto: "https://"

vaultwarden_default_config:
  domain: ~
  sends_allowed: true
  disable_icon_download: false
  signups_allowed: false
  signups_verify: false
  signups_verify_resend_time: 3600
  signups_verify_resend_limit: 6
  invitations_allowed: true
  password_iterations: 100000
  show_password_hint: true
  admin_token: ~
  invitation_org_name: Vaultwarden
  ip_header: X-Real-IP
  icon_cache_ttl: 2592000
  icon_cache_negttl: 259200
  icon_download_timeout: 10
  icon_blacklist_non_global_ips: true
  disable_2fa_remember: false
  authenticator_disable_time_drift: false
  require_device_email: false
  reload_templates: false
  log_timestamp_format: '%Y-%m-%d %H:%M:%S.%3f'
  disable_admin_token: false
  _enable_yubico: false
  _enable_duo: false
  _enable_smtp: true
  smtp_host: ~
  smtp_ssl: false
  smtp_explicit_tls: false
  smtp_port: 25
  smtp_from: ~
  smtp_from_name: Vaultwarden
  smtp_timeout: 15
  smtp_accept_invalid_certs: false
  smtp_accept_invalid_hostnames: false
  _enable_email_2fa: true
  email_token_size: 6
  email_expiration_time: 600
  email_attempts_limit: 3
