---
# All variables in this role are prefixed with 'blog_'
#
# Default task prefix to display during play
blog_task_prefix: "=== GHOST BLOG ==="

# Domain settings
blog_domain_name: "blog.example.com"
blog_url: "https://{{ blog_domain_name }}"

# Ghost blog local data directory
blog_path_base: "/opt/ghost"
blog_path_data: "{{ blog_path_base }}/data"
blog_path_env: "{{ blog_path_base }}/ghost.env"

# Template
blog_template_env: "ghost.env.j2"

# Container settings
ghost_version: "3.25.0"
blog_container_image: "ghost:{{ ghost_version }}"
blog_container_name: "ghost-blog"
blog_container_pull: "no"
blog_container_recreate: "no"
blog_container_restart_policy: "always"
blog_container_state: "started"
blog_container_labels_complete: "{{ blog_container_labels_base | combine(blog_container_labels) }}"
blog_container_labels_base:
  version: "{{ ghost_version }}"
blog_container_port: '2368'
blog_container_data: "/var/lib/ghost/content"
blog_container_ports: 
  - "{{ blog_bind_addr }}:{{ blog_bind_port }}:{{ blog_container_port }}"

# Environment variables settings
blog_env_url: "{{ blog_url }}"
# User defined variable settings:
blog_env_extra: {}

# Listen settings
blog_bind_addr: '127.0.0.1'
blog_bind_port: '2368'
